### ISSUE TITLE
/ct/page_* でリンクにならない

### ISSUE THREAD

**Issue by smasato** [smasato/manaba2kdb#1]
`https://manaba.tsukuba.ac.jp/ct/page_*` で科目番号がリンクにならない

**Comment by mkobayashime** [comment]
このIssueについて何か進展はありますでしょうか?
`manifest.json`の`matches`に`https://manaba.tsukuba.ac.jp/ct/page_*`を追加すれば解決すると思うのですが…

**Comment by smasato** [comment]
@mkobayashime 
対応するのを忘れていました。
#3 で修正しました。
