### ISSUE TITLE
シラバスのリンクが最新版でない

### ISSUE THREAD

**Issue by mkobayashime** [smasato/manaba2kdb#2]
https://github.com/smasato/manaba2kdb/blob/804c5a2d8a97ae983fb1cb9ab88c45a3353db436/src/script.js#L26

現在の実装ではこちらの記述の通り末尾が`/jpn/`の公式版シラバスへのリンクが貼られていますが、KdBで科目番号をクリックした際にデフォルトで表示されるものは公式版ではなく最新版であることなどから、最新版のシラバスを確認したいというニーズの方が多いのではないかと思います。
リンク末尾を`/jpn/0/`とすれば最新版へのリンクとなりますが、こちらに変更することをご検討いただけないでしょうか?

**Comment by smasato** [comment]
@mkobayashime 
ご提案いただきありがとうございます。
たしかに、最新版のシラバスが表示されたほうがいいので #4 で修正しました。
